default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  password: postgres
  poo: 5


development:
  <<: *default
  database: employee_manegement_development

test:
  <<: *default
  database: employee_manegement_test

production:
  <<: *default
  database: employee_manegement_production
  username: employee_manegement
  password: <%= ENV["EMPLOYEE_MANEGEMENT_DATABASE_PASSWORD"] %>
